mv api.c api.cpp
mv arrays.c arrays.cpp
mv clear.c clear.cpp
mv clip.c clip.cpp
mv error.c error.cpp
mv get.c get.cpp
mv glu.c glu.cpp
mv glx.c glx.cpp
mv image_util.c image_util.cpp
mv init.c init.cpp
mv light.c light.cpp
mv list.c list.cpp
mv matrix.c matrix.cpp
mv mech.c mech.cpp
mv memory.c memory.cpp
mv misc.c misc.cpp
mv msghandling.c msghandling.cpp
mv oscontext.c oscontext.cpp
mv select.c select.cpp
mv specbuf.c specbuf.cpp
mv texture.c texture.cpp
mv vertex.c vertex.cpp
mv x11.c x11.cpp
mv zbuffer.c zbuffer.cpp
mv zdither.c zdither.cpp
mv zline.c zline.cpp
mv zmath.c zmath.cpp
mv ztriangle.c ztriangle.cpp
